name: autofix.ci # needed to securely identify the workflow

on: [push, pull_request]

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

permissions:
  contents: read

jobs:
  autofix:
    name: Autofix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v6
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Pull environment variables
        run: bun vercel env pull --environment development .env --token ${{ secrets.VERCEL_TOKEN }}
      - name: Migrate Biome schema
        run: bun biome migrate --write
      - name: Fix linting errors
        run: bun run lint:fix
      - name: Format with Prettier
        run: bun run format:write
      - name: Fix Knip issues
        run: bun run --env-file=.env knip --fix
      - name: Run autofix.ci
        uses: autofix-ci/action@v1
        with:
          commit-message: 'refactor: apply automatic fixes'
